# Site settings
title: 我还能吃！
description: An AR game for Android
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 15331010, 15331034, 15331048
user_description: SYSU, Software Engineer, 2015
user_title: An AR game for Android
email: 648751764@qq.com
twitter_username: 
github_username:  
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
